baseURL = "https://olycats.github.io/"
languageCode = "en-us"
title = "olycats' blog"
theme = "blackburn"

[permalinks]
  post = "/:filename/"

[blackfriday]
hrefTargetBlank = true
extensions = ["hardLineBreak"]
extensionsmask = ["autolink"]

##########################################
############ THEME BLACKBURN #############
##########################################

copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[params]
  subtitle = "Personal Blog"
  brand = "olycats"
  googleAnalytics = "UA-110628235-1" #Your Google Analytics tracking ID

  # CSS name for highlight.js
  highlightjs = "tomorrow-night-eighties"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "2006/01/02"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
#  [[menu.main]]
#    name = "Posts"
#    pre = "<i class='fa fa-list fa-fw'></i>"
#    weight = 2
#    identifier = "post"
#    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Categories"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 4
    identifier = "category"
    url = "/categories/"
#  [[menu.main]]
#    name = "Tags"
#    pre = "<i class='fa fa-tags fa-fw'></i>"
#    weight = ""
#    identifier = "tag"
#    url = "/tags/"

[social]
  linkedin = "olycats"
  github = "olycats"

